name: flutter_webview_plugin_example
description: Demonstrates how to use the flutter_webview_plugin plugin.

version: 0.0.1+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.3.10+1

flutter:
  uses-material-design: true
